import './index/index'
import './header/headerController'
import '../pages/index/modules/music-player/music-player.js'
import '../pages/index/modules/testimonials/testimonials.js'
import '../pages/index/modules/music-player/nouislider.min.js'
